export enum TimeZoneEnum {
  // us
  'America/Adak' = 0,
  'America/Anchorage' = 1,
  'America/Boise' = 2,
  'America/Chicago' = 3,
  'America/Denver' = 4,
  'America/Detroit' = 5,
  'America/Indiana/Indianapolis' = 6,
  'America/Indiana/Knox' = 7,
  'America/Indiana/Marengo' = 8,
  'America/Indiana/Petersburg' = 9,
  'America/Indiana/Tell_City' = 10,
  'America/Indiana/Vevay' = 11,
  'America/Indiana/Vincennes' = 12,
  'America/Indiana/Winamac' = 13,
  'America/Juneau' = 14,
  'America/Kentucky/Louisville' = 15,
  'America/Kentucky/Monticello' = 16,
  'America/Los_Angeles' = 17,
  'America/Menominee' = 18,
  'America/Metlakatla' = 19,
  'America/New_York' = 20,
  'America/Nome' = 21,
  'America/North_Dakota/Beulah' = 22,
  'America/North_Dakota/Center' = 23,
  'America/North_Dakota/New_Salem' = 24,
  'America/Phoenix' = 25,
  'America/Sitka' = 26,
  'America/Yakutat' = 27,
  'Pacific/Honolulu' = 28,
  // canada
  'America/Atikokan' = 29,
  'America/Blanc-Sablon' = 30,
  'America/Cambridge_Bay' = 31,
  'America/Creston' = 32,
  'America/Dawson' = 33,
  'America/Dawson_Creek' = 34,
  'America/Edmonton' = 35,
  'America/Fort_Nelson' = 36,
  'America/Glace_Bay' = 37,
  'America/Goose_Bay' = 38,
  'America/Halifax' = 39,
  'America/Inuvik' = 40,
  'America/Iqaluit' = 41,
  'America/Moncton' = 42,
  'America/Nipigon' = 43,
  'America/Pangnirtung' = 44,
  'America/Rainy_River' = 45,
  'America/Rankin_Inlet' = 46,
  'America/Regina' = 47,
  'America/Resolute' = 48,
  'America/St_Johns' = 49,
  'America/Swift_Current' = 50,
  'America/Thunder_Bay' = 51,
  'America/Toronto' = 52,
  'America/Vancouver' = 53,
  'America/Whitehorse' = 54,
  'America/Winnipeg' = 55,
  'America/Yellowknife' = 56,

  // india
  'Asia/Calcutta' = 57,
  // utc
  'Default' = 58
}

export enum SkinEnum {
  Skin1 = 1,
  Skin2 = 2,
  Skin3 = 3,
  Skin4 = 4,
  Skin5 = 5,
  Skin6 = 6,
  Skin7 = 7
}
